/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SafetyCheckRouteImport } from './routes/safety-check'
import { Route as PhrasesRouteImport } from './routes/phrases'
import { Route as PhoneCheckRouteImport } from './routes/phone-check'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AwarenessRouteImport } from './routes/awareness'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyCheckRoute = SafetyCheckRouteImport.update({
  id: '/safety-check',
  path: '/safety-check',
  getParentRoute: () => rootRouteImport,
} as any)
const PhrasesRoute = PhrasesRouteImport.update({
  id: '/phrases',
  path: '/phrases',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneCheckRoute = PhoneCheckRouteImport.update({
  id: '/phone-check',
  path: '/phone-check',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AwarenessRoute = AwarenessRouteImport.update({
  id: '/awareness',
  path: '/awareness',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/awareness': typeof AwarenessRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/phone-check': typeof PhoneCheckRoute
  '/phrases': typeof PhrasesRoute
  '/safety-check': typeof SafetyCheckRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/awareness': typeof AwarenessRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/phone-check': typeof PhoneCheckRoute
  '/phrases': typeof PhrasesRoute
  '/safety-check': typeof SafetyCheckRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/awareness': typeof AwarenessRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/phone-check': typeof PhoneCheckRoute
  '/phrases': typeof PhrasesRoute
  '/safety-check': typeof SafetyCheckRoute
  '/signup': typeof SignupRoute
  '/_app/dashboard': typeof AppDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/awareness'
    | '/demo'
    | '/login'
    | '/phone-check'
    | '/phrases'
    | '/safety-check'
    | '/signup'
    | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/awareness'
    | '/demo'
    | '/login'
    | '/phone-check'
    | '/phrases'
    | '/safety-check'
    | '/signup'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/awareness'
    | '/demo'
    | '/login'
    | '/phone-check'
    | '/phrases'
    | '/safety-check'
    | '/signup'
    | '/_app/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AwarenessRoute: typeof AwarenessRoute
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
  PhoneCheckRoute: typeof PhoneCheckRoute
  PhrasesRoute: typeof PhrasesRoute
  SafetyCheckRoute: typeof SafetyCheckRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety-check': {
      id: '/safety-check'
      path: '/safety-check'
      fullPath: '/safety-check'
      preLoaderRoute: typeof SafetyCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phrases': {
      id: '/phrases'
      path: '/phrases'
      fullPath: '/phrases'
      preLoaderRoute: typeof PhrasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone-check': {
      id: '/phone-check'
      path: '/phone-check'
      fullPath: '/phone-check'
      preLoaderRoute: typeof PhoneCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awareness': {
      id: '/awareness'
      path: '/awareness'
      fullPath: '/awareness'
      preLoaderRoute: typeof AwarenessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AwarenessRoute: AwarenessRoute,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
  PhoneCheckRoute: PhoneCheckRoute,
  PhrasesRoute: PhrasesRoute,
  SafetyCheckRoute: SafetyCheckRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
