/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AwarenessRouteImport } from './routes/awareness'
import { Route as IndexRouteImport } from './routes/index'

const AwarenessRoute = AwarenessRouteImport.update({
  id: '/awareness',
  path: '/awareness',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/awareness': typeof AwarenessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/awareness': typeof AwarenessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/awareness': typeof AwarenessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/awareness'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/awareness'
  id: '__root__' | '/' | '/awareness'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AwarenessRoute: typeof AwarenessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/awareness': {
      id: '/awareness'
      path: '/awareness'
      fullPath: '/awareness'
      preLoaderRoute: typeof AwarenessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AwarenessRoute: AwarenessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
